[workspace]
name = "logyard"
members = [
    "modules/logyard-api",
    "modules/logyard-core",
    "modules/logyard-config-toml",
    "modules/logyard-output-console",
    "modules/logyard-output-json",
    "modules/logyard-runtime",
    "modules/logyard-slf4j2",
    "modules/logyard-opentelemetry",
    "modules/logyard-spring-boot",
    "modules/logyard-spring-boot-starter",
    "modules/logyard-jul",
    "modules/logyard-system-logger",
    "modules/logyard-bom",
    "tests/logyard-integration-tests",
    "tests/logyard-adapter-canaries",
    "benchmarks/logyard-benchmarks",
]
defaultMembers = ["tests/logyard-integration-tests"]

[repositories]
central = "https://repo.maven.apache.org/maven2"
