[project]
name = "logyard-benchmarks"
version = "0.1.0-rc.2"
group = "com.logyard4j"
java = 21
main = "org.openjdk.jmh.Main"

[dependencies]
"com.logyard4j:logyard-api" = { workspace = true }
"com.logyard4j:logyard-core" = { workspace = true }
"com.logyard4j:logyard-output-console" = { workspace = true }
"com.logyard4j:logyard-output-json" = { workspace = true }
"com.logyard4j:logyard-runtime" = { workspace = true }
"com.logyard4j:logyard-slf4j2" = { workspace = true }
"org.openjdk.jmh:jmh-core" = "1.37"
"org.slf4j:slf4j-api" = "2.0.18"

[dependencies.processor]
"org.openjdk.jmh:jmh-generator-annprocess" = "1.37"

[resources]
main = ["src/main/resources"]

[build.metadata]
reproducible = true
