package com.zsumz.logyard.runtime.tools;

import com.zsumz.logyard.config.ConfigurationException;
import com.zsumz.logyard.config.loading.LogyardConfigLoader;
import org.w3c.dom.Element;

import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayDeque;
import java.util.Deque;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Converts one Log4j2 XML configuration into Logyard TOML with an honest loss report.
 *
 * <p>Converts supported appenders, routes, and patterns, reporting known differences.
 * The result is validated before emission; operators must review the migration notes.</p>
 */
final class Log4j2Migration {
    /** Component name pattern accepted by {@code service.name}. */
    private static final String SERVICE_NAME = "[A-Za-z][A-Za-z0-9_.-]{0,63}";

    record Result(String toml, List<String> notes, boolean valid, String validationError) {
    }

    private final LogbackModel model = new LogbackModel();

    static Result migrate(byte[] xml) throws IOException {
        return new Log4j2Migration().convert(Log4j2Xml.parse(xml));
    }

    private Result convert(Element root) {
        if (!Log4j2Xml.named(root, "Configuration")) {
            throw new IllegalArgumentException(
                    "root element must be <Configuration>, found <" + root.getTagName() + ">");
        }
        properties(root);
        header(root);
        unsupported(root);
        appenders(root);
        Log4j2Loggers.convert(root, model);
        String body = TomlDocumentWriter.write(model.toDocument());
        String validationError = validate(body);
        return new Result(document(body), List.copyOf(model.notes), validationError == null, validationError);
    }

    private String document(String body) {
        StringBuilder toml = new StringBuilder("# Generated by Logyard migrate-log4j2.\n");
        for (String note : model.notes) {
            toml.append("# NOTE: ").append(note).append('\n');
        }
        return toml.append('\n').append(body).toString();
    }

    private void properties(Element root) {
        for (Element container : Log4j2Xml.children(root, "Properties")) {
            for (Element property : Log4j2Xml.children(container, "Property")) {
                String name = Log4j2Xml.attribute(property, "name");
                String value = Log4j2Xml.attribute(property, "value");
                value = value == null ? Log4j2Xml.text(property) : value;
                if (name == null || value == null) {
                    model.note("a <Property> without both a name and a value was ignored");
                    continue;
                }
                model.properties.put(name, Log4j2Lookups.resolve(value, model, "property '" + name + "'"));
            }
        }
    }

    private void header(Element root) {
        String status = Log4j2Xml.attribute(root, "status");
        if (status != null) {
            model.note("Configuration status='" + status + "' corresponds to runtime.internal_status,"
                    + " which defaults to 'warn' on stderr");
        }
        String monitorInterval = Log4j2Lookups.resolve(Log4j2Xml.attribute(root, "monitorInterval"), model, "monitorInterval");
        if (monitorInterval != null) {
            try {
                int seconds = Integer.parseInt(monitorInterval);
                if (seconds < 0) throw new NumberFormatException("negative interval");
                model.runtime.put("watch", seconds > 0);
                if (seconds > 0) model.note("monitorInterval='" + monitorInterval + "' became runtime.watch;"
                        + " Logyard uses debounced file watching instead of polling");
            } catch (NumberFormatException invalid) {
                model.note("monitorInterval='" + monitorInterval + "' was not converted; choose runtime.watch explicitly");
            }
        }
        String name = Log4j2Xml.attribute(root, "name");
        if (name != null && name.matches(SERVICE_NAME)) {
            model.service.put("name", name);
        } else if (name != null) {
            model.note("the Configuration name '" + name + "' is not a valid service.name and was dropped");
        }
        if (Log4j2Xml.attribute(root, "packages") != null) {
            model.note("the packages attribute has no Logyard equivalent; Logyard discovers extensions"
                    + " through the ServiceLoader");
        }
        Log4j2Filters.report("the configuration-wide filter", root, model);
    }

    private void appenders(Element root) {
        for (Element container : Log4j2Xml.children(root, "Appenders")) {
            for (Element appender : Log4j2Xml.elements(container)) {
                Log4j2Appenders.convert(appender, model);
            }
        }
        if (model.outputs.isEmpty()) {
            model.outputs.put("console", new LinkedHashMap<>(Map.of("type", "console", "stream", "stderr")));
            model.note("no convertible appenders were found; a stderr console output was generated");
        }
    }

    /** Reports constructs anywhere in the document that have no Logyard counterpart at all. */
    private void unsupported(Element root) {
        Deque<Element> pending = new ArrayDeque<>();
        pending.push(root);
        while (!pending.isEmpty()) {
            Element element = pending.pop();
            marker(element.getTagName());
            for (Element child : Log4j2Xml.elements(element)) {
                pending.push(child);
            }
        }
    }

    private void marker(String tag) {
        String lower = tag.toLowerCase(Locale.ROOT);
        if (lower.startsWith("customlevel")) {
            model.note("<" + tag + "> has no Logyard equivalent: Logyard has five fixed levels"
                    + " (trace, debug, info, warn, error); map custom levels onto the nearest one");
        } else if (lower.equals("script") || lower.equals("scripts") || lower.equals("scriptfile")) {
            model.note("<" + tag + "> has no Logyard equivalent; scripted configuration is not supported");
        } else if (lower.equals("select") || lower.endsWith("arbiter")) {
            model.note("<" + tag + "> (a configuration arbiter) has no Logyard equivalent; hand-port its"
                    + " contents into a [profiles.*] section selected by LOGYARD_PROFILE");
        }
    }

    private String validate(String toml) {
        try {
            LogyardConfigLoader.parse(toml, "migrated-log4j2.toml", Path.of("."), System.getenv());
            return null;
        } catch (ConfigurationException failure) {
            if (failure.getMessage().contains("environment variable")) {
                model.note("the configuration references environment variables;"
                        + " validate it on the target host: " + failure.getMessage());
                return null;
            }
            return failure.getMessage();
        }
    }
}
