package com.zsumz.logyard.runtime.tools;

import com.zsumz.logyard.config.ConfigurationException;
import com.zsumz.logyard.config.loading.LogyardConfigLoader;
import org.w3c.dom.Element;

import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Converts one Logback XML configuration into Logyard TOML with an honest loss report. */
final class LogbackMigration {
    record Result(String toml, List<String> notes, boolean valid, String validationError) {
    }

    private final LogbackModel model = new LogbackModel();

    static Result migrate(byte[] xml) throws IOException {
        return new LogbackMigration().convert(LogbackXml.parse(xml));
    }

    private Result convert(Element root) {
        if (!root.getTagName().equals("configuration")) {
            throw new IllegalArgumentException("root element must be <configuration>, found <" + root.getTagName() + ">");
        }
        properties(root);
        header(root);
        for (Element appender : LogbackXml.children(root, "appender")) {
            LogbackAppenders.convert(appender, model);
        }
        if (model.outputs.isEmpty()) {
            model.outputs.put("console", new LinkedHashMap<>(Map.of("type", "console", "stream", "stderr")));
            model.note("no convertible appenders were found; a stderr console output was generated");
        }
        loggers(root, model.loggers, "");
        profiles(root);
        String body = TomlDocumentWriter.write(model.toDocument());
        String validationError = validate(body);
        StringBuilder toml = new StringBuilder("# Generated by Logyard migrate-logback.\n");
        for (String note : model.notes) {
            toml.append("# NOTE: ").append(note).append('\n');
        }
        toml.append('\n').append(body);
        return new Result(toml.toString(), List.copyOf(model.notes), validationError == null, validationError);
    }

    private void properties(Element root) {
        List<Element> declarations = new ArrayList<>(LogbackXml.children(root, "property"));
        declarations.addAll(LogbackXml.children(root, "variable"));
        for (Element property : declarations) {
            String name = LogbackXml.attribute(property, "name");
            String value = LogbackXml.attribute(property, "value");
            if (name != null && value != null) {
                model.properties.put(name, model.substitute(value));
            } else {
                model.note("a <property> without name and value attributes was ignored");
            }
        }
    }

    private void header(Element root) {
        if ("true".equalsIgnoreCase(String.valueOf(LogbackXml.attribute(root, "scan")))) {
            model.runtime.put("watch", Boolean.TRUE);
            if (LogbackXml.attribute(root, "scanPeriod") != null) {
                model.note("scanPeriod was dropped: Logyard watches the file and debounces changes"
                        + " (runtime.reload_debounce)");
            }
        }
        String contextName = LogbackXml.childText(root, "contextName");
        if (contextName != null) {
            model.service.put("name", model.substitute(contextName));
        }
        if (!LogbackXml.children(root, "include").isEmpty()) {
            model.note("<include> is not supported; merge the included fragments before migrating");
        }
        if (!LogbackXml.children(root, "turboFilter").isEmpty()) {
            model.note("<turboFilter> has no Logyard equivalent; consider [filters] sampling or rate_limit");
        }
        if (LogbackXml.child(root, "statusListener") != null) {
            model.note("<statusListener> maps to runtime.internal_status (default 'warn' on stderr)");
        }
    }

    private void loggers(Element container, Map<String, Object> target, String context) {
        Element rootLogger = LogbackXml.child(container, "root");
        if (rootLogger != null) {
            target.put("root", rule(rootLogger, "root logger" + context, true));
        }
        for (Element logger : LogbackXml.children(container, "logger")) {
            String name = LogbackXml.attribute(logger, "name");
            if (name == null) {
                model.note("a <logger> without a name attribute was ignored");
                continue;
            }
            Map<String, Object> rule = rule(logger, "logger '" + name + "'" + context, false);
            if (!rule.isEmpty()) {
                target.put(name, rule);
            }
        }
    }

    private Map<String, Object> rule(Element logger, String context, boolean isRoot) {
        Map<String, Object> rule = new LinkedHashMap<>();
        String level = LogbackXml.attribute(logger, "level");
        if (level != null) {
            rule.put("level", LogbackLevels.map(level, model, context));
        }
        List<String> outputs = new ArrayList<>();
        for (Element reference : LogbackXml.children(logger, "appender-ref")) {
            String resolved = resolveAppender(reference.getAttribute("ref"));
            if (resolved == null) {
                model.note(context + ": appender-ref '" + reference.getAttribute("ref")
                        + "' does not resolve to a converted output and was dropped");
            } else if (!outputs.contains(resolved)) {
                outputs.add(resolved);
            }
        }
        if (!outputs.isEmpty()) {
            rule.put("outputs", outputs);
            if (!isRoot && !"false".equals(LogbackXml.attribute(logger, "additivity"))) {
                model.note(context + ": Logyard logger outputs replace inherited outputs instead of"
                        + " adding to them (Logback additivity)");
            }
        }
        return rule;
    }

    private String resolveAppender(String name) {
        String current = name;
        for (int hops = 0; hops < 8 && current != null; hops++) {
            if (model.outputs.containsKey(current.toLowerCase(java.util.Locale.ROOT))
                    && !model.appenderAliases.containsKey(current)) {
                break;
            }
            String next = model.appenderAliases.get(current);
            if (next == null || next.equals(current)) {
                current = next;
                break;
            }
            current = next;
        }
        return current != null && model.outputs.containsKey(current.toLowerCase(java.util.Locale.ROOT))
                ? current.toLowerCase(java.util.Locale.ROOT)
                : null;
    }

    private void profiles(Element root) {
        for (Element profile : LogbackXml.children(root, "springProfile")) {
            String names = LogbackXml.attribute(profile, "name");
            if (names == null) {
                continue;
            }
            for (String name : names.split(",")) {
                String trimmed = name.trim();
                if (trimmed.isEmpty()) {
                    continue;
                }
                if (trimmed.startsWith("!")) {
                    model.note("springProfile '" + trimmed + "': negated profiles have no Logyard"
                            + " equivalent and were skipped");
                    continue;
                }
                if (!LogbackXml.children(profile, "appender").isEmpty()) {
                    model.note("springProfile '" + trimmed + "': appenders inside profiles are not"
                            + " converted; declare outputs at the top level");
                }
                Map<String, Object> loggers = new LinkedHashMap<>();
                loggers(profile, loggers, " (profile '" + trimmed + "')");
                if (!loggers.isEmpty()) {
                    model.profiles
                            .computeIfAbsent(trimmed, ignored -> new LinkedHashMap<>())
                            .put("loggers", loggers);
                }
            }
        }
    }

    private String validate(String toml) {
        try {
            LogyardConfigLoader.parse(toml, "migrated-logback.toml", Path.of("."), System.getenv());
            return null;
        } catch (ConfigurationException failure) {
            if (failure.getMessage().contains("environment variable")) {
                model.note("the configuration references environment variables;"
                        + " validate it on the target host: " + failure.getMessage());
                return null;
            }
            return failure.getMessage();
        }
    }
}
