<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.micronaut.platform</groupId>
    <artifactId>micronaut-parent</artifactId>
    <version>4.10.9</version>
  </parent>

  <groupId>com.zsumz.logyard.examples</groupId>
  <artifactId>logyard-micronaut-example</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>${packaging}</packaging>

  <properties>
    <packaging>jar</packaging>
    <jdk.version>21</jdk.version>
    <release.version>21</release.version>
    <micronaut.version>4.10.9</micronaut.version>
    <micronaut.runtime>netty</micronaut.runtime>
    <exec.mainClass>com.zsumz.logyard.examples.micronaut.MicronautExampleApplication</exec.mainClass>
    <logyard.version>0.7.0-SNAPSHOT</logyard.version>
    <logyard.repository>file://${project.basedir}/../../target/release-bundle</logyard.repository>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.zsumz.logyard</groupId>
        <artifactId>logyard-bom</artifactId>
        <version>${logyard.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-http-server-netty</artifactId>
    </dependency>
    <dependency>
      <groupId>io.micronaut.serde</groupId>
      <artifactId>micronaut-serde-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>com.zsumz.logyard</groupId>
      <artifactId>logyard-slf4j2</artifactId>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
      <id>staged-logyard</id>
      <url>${logyard.repository}</url>
      <releases>
        <enabled>true</enabled>
        <checksumPolicy>fail</checksumPolicy>
      </releases>
      <snapshots>
        <enabled>true</enabled>
        <checksumPolicy>fail</checksumPolicy>
      </snapshots>
    </repository>
  </repositories>

  <build>
    <plugins>
      <plugin>
        <groupId>io.micronaut.maven</groupId>
        <artifactId>micronaut-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.graalvm.buildtools</groupId>
        <artifactId>native-maven-plugin</artifactId>
        <configuration>
          <buildArgs combine.children="append">
            <buildArg>--initialize-at-run-time=com.zsumz.logyard,org.slf4j,io.netty.buffer,io.netty.handler.codec.http2.Http2CodecUtil</buildArg>
          </buildArgs>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <compilerArgs>
            <arg>-Amicronaut.processing.group=com.zsumz.logyard.examples</arg>
            <arg>-Amicronaut.processing.module=logyard-micronaut-example</arg>
          </compilerArgs>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
