<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.logyard4j</groupId>
        <artifactId>logyard-quarkus-parent</artifactId>
        <version>0.1.0-rc.1</version>
    </parent>

    <artifactId>logyard-quarkus-deployment</artifactId>
    <name>Logyard Quarkus Deployment</name>
    <description>Build-time wiring for the Logyard Quarkus extension.</description>
    <url>https://logyard4j.com</url>

    <scm>
        <connection>scm:git:https://github.com/zsumz/logyard.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/zsumz/logyard.git</developerConnection>
        <tag>v${project.version}</tag>
        <url>https://github.com/zsumz/logyard</url>
    </scm>

    <dependencies>
        <dependency>
            <groupId>com.logyard4j</groupId>
            <artifactId>logyard-quarkus</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-core-deployment</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc-deployment</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>io.quarkus</groupId>
                                    <artifactId>quarkus-extension-processor</artifactId>
                                </path>
                            </annotationProcessorPaths>
                            <annotationProcessorPathsUseDepMgmt>true</annotationProcessorPathsUseDepMgmt>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Automatic-Module-Name>com.logyard4j.quarkus.deployment</Automatic-Module-Name>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
