[project]
name = "logyard-spring-boot-starter"
version = "0.1.0-rc.1"
group = "com.logyard4j"
java = 21
description = "Opinionated Spring Boot starter with Logyard as the sole SLF4J 2 logging provider."
url = "https://logyard4j.com"
issues = "https://github.com/logyard4j/logyard/issues"
license = "Apache-2.0"

[project.scm]
url = "https://github.com/logyard4j/logyard"
connection = "scm:git:https://github.com/logyard4j/logyard.git"
developerConnection = "scm:git:ssh://git@github.com/logyard4j/logyard.git"

[project.developers.zsumz]
name = "zsumz"
email = "shawn@zsumz.com"

[dependencies.api]
"com.logyard4j:logyard-api" = { workspace = true }
"com.logyard4j:logyard-slf4j2" = { workspace = true }
"com.logyard4j:logyard-spring-boot" = { workspace = true }
"org.springframework.boot:spring-boot-starter" = { version = "3.5.16", exclude = ["org.springframework.boot:spring-boot-starter-logging"] }

[resources]
main = ["src/main/resources"]

[build.metadata]
reproducible = true

[package]
mode = "jar"
sources = true
javadoc = true

[package.manifest]
"Automatic-Module-Name" = "com.logyard4j.spring.boot.starter"

[publish.signing]
method = "gpg"
keyId = "EC8E4D26598A0373"

[publish.central]
tokenEnv = "ZOLT_CENTRAL_TOKEN"
mode = "manual"
