[project]
name = "logyard-quarkus-example"
version = "1.0.0-SNAPSHOT"
group = "com.logyard4j.logyard.examples"
java = 21

[platforms]
"com.logyard4j:logyard-bom" = "0.1.0-rc.2"
"io.quarkus.platform:quarkus-bom" = "3.37.3"

[dependencies]
"io.quarkus:quarkus-rest" = { managed = true }
"com.logyard4j:logyard-quarkus" = { managed = true }

[dependencies.test]
"io.quarkus:quarkus-junit" = { managed = true }
"io.rest-assured:rest-assured" = { managed = true }

[resources]
main = ["src/main/resources"]
test = ["src/test/resources"]

[package]
mode = "quarkus"
